### ISSUE TITLE
BUTTONS

### ISSUE THREAD

**Issue by realbenben** [realbenben/3wa-projet#9]
- [x] changer couleur en var
- [x] changer la taille  en ex:
```css
.button-small{
       font-size:12px
}
```
- [x] text in middle
